// original script by BangaBob, heavily modified by soulkobk

if !(isServer) exitWith {};

// Set INSIDE probability of loot spawning 1-100%
_insideProbability = (100 / 2); // 50%
// Set OUTSIDE probability of loot spawning 1-100%
_outsideProbability = (100 / 3); // 33.33^%
// Show loot position and type on map (Debugging)
_showLoot = false;
// Set Weapon loot: Primary weapons, secondary weapons, Sidearms.
weaponsLoot =
[
	// "arifle_AK12_F", // AK-12 7.62 mm PRIMARYWEAPON"
	// "arifle_AK12_GL_F", // AK-12 GL 7.62 mm PRIMARYWEAPON"
	// "arifle_AKM_F", // AKM 7.62 mm PRIMARYWEAPON"
	"arifle_AKS_F", // AKS-74U 5.45 mm PRIMARYWEAPON"
	"arifle_AKS_F", // AKS-74U 5.45 mm PRIMARYWEAPON"
	// "arifle_ARX_blk_F", // Type 115 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_ARX_ghex_F", // Type 115 6.5 mm (Green Hex) PRIMARYWEAPON"
	// "arifle_ARX_hex_F", // Type 115 6.5 mm (Hex) PRIMARYWEAPON"
	// "arifle_CTARS_blk_F", // CAR-95-1 5.8mm (Black) PRIMARYWEAPON"
	// "arifle_CTARS_blk_Pointer_F", // CAR-95-1 5.8mm (Black) PRIMARYWEAPON"
	// "arifle_CTARS_ghex_F", // CAR-95-1 5.8mm (Green Hex) PRIMARYWEAPON"
	// "arifle_CTARS_hex_F", // CAR-95-1 5.8mm (Hex) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ACO_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ACO_Pointer_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ACO_Pointer_Snds_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ARCO_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ARCO_Pointer_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_ARCO_Pointer_Snds_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	"arifle_CTAR_blk_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_blk_Pointer_F", // CAR-95 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_ghex_F", // CAR-95 5.8 mm (Green Hex) PRIMARYWEAPON"
	// "arifle_CTAR_GL_blk_ACO_F", // CAR-95 GL 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_GL_blk_ACO_Pointer_Snds_F", // CAR-95 GL 5.8 mm (Black) PRIMARYWEAPON"
	"arifle_CTAR_GL_blk_F", // CAR-95 GL 5.8 mm (Black) PRIMARYWEAPON"
	// "arifle_CTAR_GL_ghex_F", // CAR-95 GL 5.8 mm (Green Hex) PRIMARYWEAPON"
	// "arifle_CTAR_GL_hex_F", // CAR-95 GL 5.8 mm (Hex) PRIMARYWEAPON"
	// "arifle_CTAR_hex_F", // CAR-95 5.8 mm (Hex) PRIMARYWEAPON"
	// "arifle_Katiba_ACO_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_ACO_pointer_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_ACO_pointer_snds_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_ARCO_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_ARCO_pointer_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_ARCO_pointer_snds_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_C_ACO_F", // Katiba Carbine 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_C_ACO_pointer_F", // Katiba Carbine 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_C_ACO_pointer_snds_F", // Katiba Carbine 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_C_F", // Katiba Carbine 6.5 mm PRIMARYWEAPON"
	"arifle_Katiba_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_GL_ACO_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_GL_ACO_pointer_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_GL_ACO_pointer_snds_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_GL_ARCO_pointer_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	"arifle_Katiba_GL_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_GL_Nstalker_pointer_F", // Katiba GL 6.5 mm PRIMARYWEAPON"
	// "arifle_Katiba_pointer_F", // Katiba 6.5 mm PRIMARYWEAPON"
	// "arifle_Mk20C_ACO_F", // Mk20C 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20C_ACO_pointer_F", // Mk20C 5.56 mm (Camo) PRIMARYWEAPON"
	"arifle_Mk20C_F", // Mk20C 5.56 mm (Camo) PRIMARYWEAPON"
	"arifle_Mk20C_plain_F", // Mk20C 5.56 mm PRIMARYWEAPON"
	// "arifle_Mk20_ACO_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_ACO_pointer_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	"arifle_Mk20_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_GL_ACO_F", // Mk20 EGLM 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_GL_F", // Mk20 EGLM 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_GL_MRCO_pointer_F", // Mk20 EGLM 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_GL_plain_F", // Mk20 EGLM 5.56 mm PRIMARYWEAPON"
	// "arifle_Mk20_Holo_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_MRCO_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_Mk20_MRCO_plain_F", // Mk20 5.56 mm PRIMARYWEAPON"
	// "arifle_Mk20_MRCO_pointer_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	"arifle_Mk20_plain_F", // Mk20 5.56 mm PRIMARYWEAPON"
	// "arifle_Mk20_pointer_F", // Mk20 5.56 mm (Camo) PRIMARYWEAPON"
	// "arifle_MXC_ACO_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_ACO_pointer_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_ACO_pointer_snds_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_Black_F", // MXC 6.5 mm (Black) PRIMARYWEAPON"
	"arifle_MXC_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_Holo_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_Holo_pointer_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_Holo_pointer_snds_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXC_khk_ACO_F", // MXC 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MXC_khk_ACO_Pointer_Snds_F", // MXC 6.5 mm (Khaki) PRIMARYWEAPON"
	"arifle_MXC_khk_F", // MXC 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MXC_khk_Holo_Pointer_F", // MXC 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MXC_SOS_point_snds_F", // MXC 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_Black_F", // MXM 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MXM_DMS_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_DMS_LP_BI_snds_F", // MXM 6.5 mm PRIMARYWEAPON"
	"arifle_MXM_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_Hamr_LP_BI_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_Hamr_pointer_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_khk_F", // MXM 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MXM_khk_MOS_Pointer_Bipod_F", // MXM 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MXM_RCO_pointer_snds_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MXM_SOS_pointer_F", // MXM 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_ACO_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_ACO_pointer_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_ACO_pointer_snds_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_Black_F", // MX 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MX_Black_Hamr_pointer_F", // MX 6.5 mm (Black) PRIMARYWEAPON"
	"arifle_MX_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_ACO_F", // MX 3GL 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_ACO_pointer_F", // MX 3GL 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_Black_F", // MX 3GL 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MX_GL_Black_Hamr_pointer_F", // MX 3GL 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MX_GL_F", // MX 3GL 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_Hamr_pointer_F", // MX 3GL 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_Holo_pointer_snds_F", // MX 3GL 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_GL_khk_ACO_F", // MX 3GL 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_GL_khk_F", // MX 3GL 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_GL_khk_Hamr_Pointer_F", // MX 3GL 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_GL_khk_Holo_Pointer_Snds_F", // MX 3GL 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_Hamr_pointer_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_Holo_pointer_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_khk_ACO_Pointer_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_ACO_Pointer_Snds_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_Hamr_Pointer_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_Hamr_Pointer_Snds_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_Holo_Pointer_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_khk_Pointer_F", // MX 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_pointer_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_RCO_pointer_snds_F", // MX 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_SW_Black_F", // MX SW 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MX_SW_Black_Hamr_pointer_F", // MX SW 6.5 mm (Black) PRIMARYWEAPON"
	// "arifle_MX_SW_F", // MX SW 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_SW_F", // MX SW 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_SW_Hamr_pointer_F", // MX SW 6.5 mm PRIMARYWEAPON"
	// "arifle_MX_SW_khk_F", // MX SW 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_SW_khk_Pointer_F", // MX SW 6.5 mm (Khaki) PRIMARYWEAPON"
	// "arifle_MX_SW_pointer_F", // MX SW 6.5 mm PRIMARYWEAPON"
	"arifle_SDAR_F", // SDAR 5.56 mm PRIMARYWEAPON"
	"arifle_SPAR_01_blk_F", // SPAR-16 5.56 mm (Black) PRIMARYWEAPON"
	"arifle_SPAR_01_GL_blk_F", // SPAR-16 GL 5.56 mm (Black) PRIMARYWEAPON"
	// "arifle_SPAR_01_GL_khk_F", // SPAR-16 GL 5.56 mm (Khaki) PRIMARYWEAPON"
	// "arifle_SPAR_01_GL_snd_F", // SPAR-16 GL 5.56 mm (Sand) PRIMARYWEAPON"
	// "arifle_SPAR_01_khk_F", // SPAR-16 5.56 mm (Khaki) PRIMARYWEAPON"
	// "arifle_SPAR_01_snd_F", // SPAR-16 5.56 mm (Sand) PRIMARYWEAPON"
	// "arifle_SPAR_02_blk_F", // SPAR-16S 5.56 mm (Black) PRIMARYWEAPON"
	// "arifle_SPAR_02_khk_F", // SPAR-16S 5.56 mm (Khaki) PRIMARYWEAPON"
	// "arifle_SPAR_02_snd_F", // SPAR-16S 5.56 mm (Sand) PRIMARYWEAPON"
	// "arifle_SPAR_03_blk_F", // SPAR-17 7.62 mm (Black) PRIMARYWEAPON"
	// "arifle_SPAR_03_khk_F", // SPAR-17 7.62 mm (Khaki) PRIMARYWEAPON"
	// "arifle_SPAR_03_snd_F", // SPAR-17 7.62 mm (Sand) PRIMARYWEAPON"
	// "arifle_TRG20_ACO_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG20_ACO_Flash_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG20_ACO_pointer_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG20_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG20_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG20_Holo_F", // TRG-20 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_ACO_pointer_F", // TRG-21 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_ARCO_pointer_F", // TRG-21 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_F", // TRG-21 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_F", // TRG-21 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_GL_ACO_pointer_F", // TRG-21 EGLM 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_GL_F", // TRG-21 EGLM 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_GL_MRCO_F", // TRG-21 EGLM 5.56 mm PRIMARYWEAPON"
	// "arifle_TRG21_MRCO_F", // TRG-21 5.56 mm PRIMARYWEAPON"
	// "hgun_PDW2000_F", // PDW2000 9 mm PRIMARYWEAPON"
	// "hgun_PDW2000_Holo_F", // PDW2000 9 mm PRIMARYWEAPON"
	// "hgun_PDW2000_Holo_snds_F", // PDW2000 9 mm PRIMARYWEAPON"
	// "hgun_PDW2000_snds_F", // PDW2000 9 mm PRIMARYWEAPON"
	// "LMG_03_F", // LIM-85 5.56 mm PRIMARYWEAPON"
	// "LMG_Mk200_BI_F", // Mk200 6.5 mm PRIMARYWEAPON"
	"LMG_Mk200_F", // Mk200 6.5 mm PRIMARYWEAPON"
	// "LMG_Mk200_LP_BI_F", // Mk200 6.5 mm PRIMARYWEAPON"
	// "LMG_Mk200_MRCO_F", // Mk200 6.5 mm PRIMARYWEAPON"
	// "LMG_Mk200_pointer_F", // Mk200 6.5 mm PRIMARYWEAPON"
	// "LMG_Zafir_ARCO_F", // Zafir 7.62 mm PRIMARYWEAPON"
	"LMG_Zafir_F", // Zafir 7.62 mm PRIMARYWEAPON"
	// "LMG_Zafir_pointer_F", // Zafir 7.62 mm PRIMARYWEAPON"
	// "MMG_01_hex_ARCO_LP_F", // Navid 9.3 mm (Hex) PRIMARYWEAPON"
	// "MMG_01_hex_F", // Navid 9.3 mm (Hex) PRIMARYWEAPON"
	// "MMG_01_tan_F", // Navid 9.3 mm (Tan) PRIMARYWEAPON"
	// "MMG_02_black_F", // SPMG .338 (Black) PRIMARYWEAPON"
	// "MMG_02_black_RCO_BI_F", // SPMG .338 (Black) PRIMARYWEAPON"
	// "MMG_02_camo_F", // SPMG .338 (MTP) PRIMARYWEAPON"
	// "MMG_02_sand_F", // SPMG .338 (Sand) PRIMARYWEAPON"
	// "MMG_02_sand_RCO_LP_F", // SPMG .338 (Sand) PRIMARYWEAPON"
	// "SMG_01_ACO_F", // Vermin SMG .45 ACP PRIMARYWEAPON"
	// "SMG_01_F", // Vermin SMG .45 ACP PRIMARYWEAPON"
	// "SMG_01_Holo_F", // Vermin SMG .45 ACP PRIMARYWEAPON"
	// "SMG_01_Holo_pointer_snds_F", // Vermin SMG .45 ACP PRIMARYWEAPON"
	// "SMG_02_ACO_F", // Sting 9 mm PRIMARYWEAPON"
	// "SMG_02_ARCO_pointg_F", // Sting 9 mm PRIMARYWEAPON"
	// "SMG_02_F", // Sting 9 mm PRIMARYWEAPON"
	// "SMG_05_F", // Protector 9 mm PRIMARYWEAPON"
	// "srifle_DMR_01_ACO_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_ARCO_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_DMS_BI_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_DMS_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_DMS_snds_BI_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_DMS_snds_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_MRCO_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_01_SOS_F", // Rahim 7.62 mm PRIMARYWEAPON"
	// "srifle_DMR_02_ACO_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_02_ARCO_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_02_camo_AMS_LP_F", // MAR-10 .338 (Camo) PRIMARYWEAPON"
	// "srifle_DMR_02_camo_F", // MAR-10 .338 (Camo) PRIMARYWEAPON"
	// "srifle_DMR_02_DMS_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_02_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_02_MRCO_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_02_sniper_AMS_LP_S_F", // MAR-10 .338 (Sand) PRIMARYWEAPON"
	// "srifle_DMR_02_sniper_F", // MAR-10 .338 (Sand) PRIMARYWEAPON"
	// "srifle_DMR_02_SOS_F", // MAR-10 .338 (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_ACO_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_AMS_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_ARCO_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_DMS_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_DMS_snds_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_khaki_F", // Mk-I EMR 7.62 mm (Khaki) PRIMARYWEAPON"
	// "srifle_DMR_03_MRCO_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_multicam_F", // Mk-I EMR 7.62 mm (Camo) PRIMARYWEAPON"
	// "srifle_DMR_03_SOS_F", // Mk-I EMR 7.62 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_03_tan_AMS_LP_F", // Mk-I EMR 7.62 mm (Sand) PRIMARYWEAPON"
	// "srifle_DMR_03_tan_F", // Mk-I EMR 7.62 mm (Sand) PRIMARYWEAPON"
	// "srifle_DMR_03_woodland_F", // Mk-I EMR 7.62 mm (Woodland) PRIMARYWEAPON"
	// "srifle_DMR_04_ACO_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_ARCO_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_DMS_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_MRCO_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_NS_LP_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_SOS_F", // ASP-1 Kir 12.7 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_04_Tan_F", // ASP-1 Kir 12.7 mm (Tan) PRIMARYWEAPON"
	// "srifle_DMR_05_ACO_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_ARCO_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_blk_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_DMS_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_DMS_snds_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_hex_F", // Cyrus 9.3 mm (Hex) PRIMARYWEAPON"
	// "srifle_DMR_05_KHS_LP_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_MRCO_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_SOS_F", // Cyrus 9.3 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_05_tan_f", // Cyrus 9.3 mm (Tan) PRIMARYWEAPON"
	// "srifle_DMR_06_camo_F", // Mk14 7.62 mm (Camo) PRIMARYWEAPON"
	// "srifle_DMR_06_camo_khs_F", // Mk14 7.62 mm (Camo) PRIMARYWEAPON"
	// "srifle_DMR_06_olive_F", // Mk14 7.62 mm (Olive) PRIMARYWEAPON"
	// "srifle_DMR_07_blk_DMS_F", // CMR-76 6.5 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_07_blk_DMS_Snds_F", // CMR-76 6.5 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_07_blk_F", // CMR-76 6.5 mm (Black) PRIMARYWEAPON"
	// "srifle_DMR_07_ghex_F", // CMR-76 6.5 mm (Green Hex) PRIMARYWEAPON"
	// "srifle_DMR_07_hex_F", // CMR-76 6.5 mm (Hex) PRIMARYWEAPON"
	// "srifle_EBR_ACO_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_ARCO_pointer_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_ARCO_pointer_snds_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_DMS_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_DMS_pointer_snds_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_Hamr_pointer_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_MRCO_LP_BI_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_MRCO_pointer_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_EBR_SOS_F", // Mk18 ABR 7.62 mm PRIMARYWEAPON"
	// "srifle_GM6_camo_F", // GM6 Lynx 12.7 mm (Camo) PRIMARYWEAPON"
	// "srifle_GM6_camo_LRPS_F", // GM6 Lynx 12.7 mm (Camo) PRIMARYWEAPON"
	// "srifle_GM6_camo_SOS_F", // GM6 Lynx 12.7 mm (Camo) PRIMARYWEAPON"
	// "srifle_GM6_F", // GM6 Lynx 12.7 mm PRIMARYWEAPON"
	// "srifle_GM6_ghex_F", // GM6 Lynx 12.7 mm (Green Hex) PRIMARYWEAPON"
	// "srifle_GM6_ghex_LRPS_F", // GM6 Lynx 12.7 mm (Green Hex) PRIMARYWEAPON"
	// "srifle_GM6_LRPS_F", // GM6 Lynx 12.7 mm PRIMARYWEAPON"
	// "srifle_GM6_SOS_F", // GM6 Lynx 12.7 mm PRIMARYWEAPON"
	// "srifle_LRR_camo_F", // M320 LRR .408 (Camo) PRIMARYWEAPON"
	// "srifle_LRR_camo_LRPS_F", // M320 LRR .408 (Camo) PRIMARYWEAPON"
	// "srifle_LRR_camo_SOS_F", // M320 LRR .408 (Camo) PRIMARYWEAPON"
	// "srifle_LRR_F", // M320 LRR .408 PRIMARYWEAPON"
	// "srifle_LRR_LRPS_F", // M320 LRR .408 PRIMARYWEAPON"
	// "srifle_LRR_SOS_F", // M320 LRR .408 PRIMARYWEAPON"
	// "srifle_LRR_tna_F", // M320 LRR .408 (Tropic) PRIMARYWEAPON"
	// "srifle_LRR_tna_LRPS_F", // M320 LRR .408 (Tropic) PRIMARYWEAPON"
	"hgun_ACPC2_F", // ACP-C2 .45 ACP SECONDARYWEAPON"
	// "hgun_ACPC2_snds_F", // ACP-C2 .45 ACP SECONDARYWEAPON"
	"hgun_P07_F", // P07 9 mm SECONDARYWEAPON"
	// "hgun_P07_khk_F", // P07 9 mm (Khaki) SECONDARYWEAPON"
	// "hgun_P07_snds_F", // P07 9 mm SECONDARYWEAPON"
	"hgun_Pistol_01_F", // PM 9 mm SECONDARYWEAPON"
	// "hgun_Pistol_heavy_01_F", // 4-five .45 ACP SECONDARYWEAPON"
	// "hgun_Pistol_heavy_01_MRD_F", // 4-five .45 ACP SECONDARYWEAPON"
	// "hgun_Pistol_heavy_01_snds_F", // 4-five .45 ACP SECONDARYWEAPON"
	"hgun_Pistol_heavy_02_F", // Zubr .45 ACP SECONDARYWEAPON"
	// "hgun_Pistol_heavy_02_Yorris_F", // Zubr .45 ACP SECONDARYWEAPON"
	// "hgun_Pistol_Signal_F", // Starter Pistol SECONDARYWEAPON"
	"hgun_Rook40_F" // Rook-40 9 mm SECONDARYWEAPON"
	// "hgun_Rook40_snds_F" // Rook-40 9 mm SECONDARYWEAPON"
];

medicalLoot =
[
	"FirstAidKit" // First Aid Kit ITEM"
];

grenadeMineLoot =
[
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"HandGrenade", // RGO Grenade MAGAZINE"
	"MiniGrenade", // RGN Grenade MAGAZINE"
	"SmokeShell", // Smoke Grenade (White) MAGAZINE"
	"SmokeShellBlue", // Smoke Grenade (Blue) MAGAZINE"
	"SmokeShellGreen", // Smoke Grenade (Green) MAGAZINE"
	"SmokeShellOrange", // Smoke Grenade (Orange) MAGAZINE"
	"SmokeShellPurple", // Smoke Grenade (Purple) MAGAZINE"
	"SmokeShellRed", // Smoke Grenade (Red) MAGAZINE"
	"SmokeShellYellow", // Smoke Grenade (Yellow) MAGAZINE"
	"APERSBoundingMine_Range_Mag", // APERS Bounding Mine MAGAZINE"
	"APERSMine_Range_Mag", // APERS Mine MAGAZINE"
	"APERSTripMine_Wire_Mag", // APERS Tripwire Mine MAGAZINE"
	"SLAMDirectionalMine_Wire_Mag", // M6 SLAM Mine MAGAZINE"
	"DemoCharge_Remote_Mag", // Explosive Charge MAGAZINE"
	"SatchelCharge_Remote_Mag", // Explosive Satchel MAGAZINE"
	"SLAMDirectionalMine_Wire_Mag" // M6 SLAM Mine MAGAZINE"
];

// Set items: Weapon attachments, first-aid, Binoculars
itemsLoot =
[
	// "muzzle_snds_338_black", // Sound Suppressor (.338, Black) MUZZLE"
	// "muzzle_snds_338_green", // Sound Suppressor (.338, Green) MUZZLE"
	// "muzzle_snds_338_sand", // Sound Suppressor (.338, Sand) MUZZLE"
	"muzzle_snds_58_blk_F", // Stealth Sound Suppressor (5.8 mm, Black) MUZZLE"
	// "muzzle_snds_58_ghex_F", // Stealth Sound Suppressor (5.8 mm, Green Hex) MUZZLE"
	// "muzzle_snds_58_hex_F", // Sound Suppressor (5.8 mm, Hex) MUZZLE"
	// "muzzle_snds_65_TI_blk_F", // Stealth Sound Suppressor (6.5 mm, Black) MUZZLE"
	// "muzzle_snds_65_TI_ghex_F", // Stealth Sound Suppressor (6.5 mm, Green Hex) MUZZLE"
	// "muzzle_snds_65_TI_hex_F", // Stealth Sound Suppressor (6.5 mm, Hex) MUZZLE"
	// "muzzle_snds_93mmg", // Sound Suppressor (9.3mm, Black) MUZZLE"
	// "muzzle_snds_93mmg_tan", // Sound Suppressor (9.3mm, Tan) MUZZLE"
	"muzzle_snds_acp", // Sound Suppressor (.45 ACP) MUZZLE"
	// "muzzle_snds_B", // Sound Suppressor (7.62 mm) MUZZLE"
	// "muzzle_snds_B_khk_F", // Sound Suppressor (7.62 mm, Khaki) MUZZLE"
	// "muzzle_snds_B_snd_F", // Sound Suppressor (7.62 mm, Sand) MUZZLE"
	"muzzle_snds_H", // Sound Suppressor (6.5 mm) MUZZLE"
	// "muzzle_snds_H_khk_F", // Sound Suppressor (6.5 mm, Khaki) MUZZLE"
	// "muzzle_snds_H_snd_F", // Sound Suppressor (6.5 mm, Sand) MUZZLE"
	"muzzle_snds_L", // Sound Suppressor (9 mm) MUZZLE"
	"muzzle_snds_M", // Sound Suppressor (5.56 mm) MUZZLE"
	// "muzzle_snds_m_khk_F", // Sound Suppressor (5.56 mm, Khaki) MUZZLE"
	// "muzzle_snds_m_snd_F", // Sound Suppressor (5.56 mm, Sand) MUZZLE"
	"optic_Aco", // ACO (Red) OPTIC"
	// "optic_ACO_grn", // ACO (Green) OPTIC"
	// "optic_ACO_grn_smg", // ACO SMG (Green) OPTIC"
	// "optic_Aco_smg", // ACO SMG (Red) OPTIC"
	"optic_AMS", // AMS (Black) OPTIC"
	// "optic_AMS_khk", // AMS (Khaki) OPTIC"
	// "optic_AMS_snd", // AMS (Sand) OPTIC"
	"optic_Arco", // ARCO OPTIC"
	// "optic_Arco_blk_F", // ARCO (Black) OPTIC"
	// "optic_Arco_ghex_F", // ARCO (Green Hex) OPTIC"
	// "optic_DMS", // DMS OPTIC"
	// "optic_DMS_ghex_F", // DMS (Green Hex) OPTIC"
	// "optic_ERCO_blk_F", // ERCO (Black) OPTIC"
	// "optic_ERCO_khk_F", // ERCO (Khaki) OPTIC"
	// "optic_ERCO_snd_F", // ERCO (Sand) OPTIC"
	"optic_Hamr", // RCO OPTIC"
	// "optic_Hamr_khk_F", // RCO (Khaki) OPTIC"
	"optic_Holosight", // Mk17 Holosight OPTIC"
	// "optic_Holosight_blk_F", // Mk17 Holosight (Black) OPTIC"
	// "optic_Holosight_khk_F", // Mk17 Holosight (Khaki) OPTIC"
	// "optic_Holosight_smg", // Mk17 Holosight SMG OPTIC"
	// "optic_Holosight_smg_blk_F", // Mk17 Holosight SMG (Black) OPTIC"
	// "optic_KHS_blk", // Kahlia (Black) OPTIC"
	// "optic_KHS_hex", // Kahlia (Hex) OPTIC"
	// "optic_KHS_old", // Kahlia (Old) OPTIC"
	// "optic_KHS_tan", // Kahlia (Tan) OPTIC"
	// "optic_LRPS", // LRPS OPTIC"
	// "optic_LRPS_ghex_F", // LRPS (Green Hex) OPTIC"
	// "optic_LRPS_tna_F", // LRPS (Tropic) OPTIC"
	"optic_MRCO", // MRCO OPTIC"
	"optic_MRD", // MRD OPTIC"
	// "optic_Nightstalker", // Nightstalker OPTIC"
	// "optic_NVS", // NVS OPTIC"
	// "optic_SOS", // MOS OPTIC"
	// "optic_SOS_khk_F", // MOS (Khaki) OPTIC"
	// "optic_tws", // TWS OPTIC"
	// "optic_tws_mg", // TWS MG OPTIC"
	"optic_Yorris" // Yorris J2 OPTIC"
];
// Set Clothing: Hats, Helmets, Uniforms
clothesLoot =
[
	"H_HelmetB", // Combat Helmet HEADGEAR"
	"H_HelmetB_black", // Combat Helmet (Black) HEADGEAR"
	"H_HelmetB_camo", // Combat Helmet (Camo) HEADGEAR"
	"H_HelmetB_desert", // Combat Helmet (Desert) HEADGEAR"
	"H_HelmetB_Enh_tna_F", // Enhanced Combat Helmet (Tropic) HEADGEAR"
	"H_HelmetB_grass", // Combat Helmet (Grass) HEADGEAR"
	"H_HelmetB_light", // Light Combat Helmet HEADGEAR"
	"H_HelmetB_light_black", // Light Combat Helmet (Black) HEADGEAR"
	"H_HelmetB_light_desert", // Light Combat Helmet (Desert) HEADGEAR"
	"H_HelmetB_light_grass", // Light Combat Helmet (Grass) HEADGEAR"
	"H_HelmetB_light_sand", // Light Combat Helmet (Sand) HEADGEAR"
	"H_HelmetB_light_snakeskin", // Light Combat Helmet (Snakeskin) HEADGEAR"
	"H_HelmetB_Light_tna_F", // Light Combat Helmet (Tropic) HEADGEAR"
	"H_HelmetB_sand", // Combat Helmet (Sand) HEADGEAR"
	"H_HelmetB_snakeskin", // Combat Helmet (Snakeskin) HEADGEAR"
	"H_HelmetB_tna_F", // Combat Helmet (Tropic) HEADGEAR"
	"H_HelmetSpecB", // Enhanced Combat Helmet HEADGEAR"
	"H_HelmetSpecB_blk", // Enhanced Combat Helmet (Black) HEADGEAR"
	"H_HelmetSpecB_paint1", // Enhanced Combat Helmet (Grass) HEADGEAR"
	"H_HelmetSpecB_paint2", // Enhanced Combat Helmet (Desert) HEADGEAR"
	"H_HelmetSpecB_sand", // Enhanced Combat Helmet (Sand) HEADGEAR"
	"H_HelmetSpecB_snakeskin", // Enhanced Combat Helmet (Snakeskin) HEADGEAR"

	"U_B_CombatUniform_mcam", // Combat Fatigues (MTP) UNIFORM"
	"U_B_CombatUniform_mcam_tshirt", // Combat Fatigues (MTP) (Tee) UNIFORM"
	"U_B_CombatUniform_mcam_vest", // Recon Fatigues (MTP) UNIFORM"
	"U_B_CombatUniform_mcam_worn", // Worn Combat Fatigues (MTP) UNIFORM"
	"U_B_CTRG_1", // CTRG Combat Uniform UNIFORM"
	"U_B_CTRG_2", // CTRG Combat Uniform (Tee) UNIFORM"
	"U_B_CTRG_3", // CTRG Combat Uniform (Rolled-up) UNIFORM"
	"U_B_CTRG_Soldier_urb_1_F", // CTRG Urban Uniform UNIFORM"
	"U_B_CTRG_Soldier_urb_2_F", // CTRG Urban Uniform (Tee) UNIFORM"
	"U_B_CTRG_Soldier_urb_3_F", // CTRG Urban Uniform (Rolled-up) UNIFORM"
	"U_B_GhillieSuit", // Ghillie Suit [NATO] UNIFORM"
	"U_B_HeliPilotCoveralls", // Heli Pilot Coveralls [NATO] UNIFORM"
	"U_B_PilotCoveralls", // Pilot Coveralls [NATO] UNIFORM"
	"U_B_T_Soldier_AR_F", // Combat Fatigues (Tropic, Tee) UNIFORM"
	"U_B_T_Soldier_F", // Combat Fatigues (Tropic) UNIFORM"
	"U_B_T_Soldier_SL_F", // Recon Fatigues (Tropic) UNIFORM"
	"U_B_Wetsuit", // Wetsuit [NATO] UNIFORM"
	// "U_I_CombatUniform", // Combat Fatigues [AAF] UNIFORM" // this is used for default uniform (spawn area) now with custom texture!
	"U_I_CombatUniform_shortsleeve", // Combat Fatigues [AAF] (Rolled-up) UNIFORM"
	"U_I_C_Soldier_Para_1_F", // Paramilitary Garb (Tee) UNIFORM"
	"U_I_C_Soldier_Para_2_F", // Paramilitary Garb (Jacket) UNIFORM"
	"U_I_C_Soldier_Para_3_F", // Paramilitary Garb (Shirt) UNIFORM"
	"U_I_C_Soldier_Para_4_F", // Paramilitary Garb (Tank Top) UNIFORM"
	"U_I_C_Soldier_Para_5_F", // Paramilitary Garb (Shorts) UNIFORM"
	"U_I_GhillieSuit", // Ghillie Suit [AAF] UNIFORM"
	"U_I_HeliPilotCoveralls", // Heli Pilot Coveralls [AAF] UNIFORM"
	"U_I_OfficerUniform", // Combat Fatigues [AAF] (Officer) UNIFORM"
	"U_I_pilotCoveralls", // Pilot Coveralls [AAF] UNIFORM"
	"U_I_Wetsuit", // Wetsuit [AAF] UNIFORM"
	"U_O_CombatUniform_ocamo", // Fatigues (Hex) [CSAT] UNIFORM"
	"U_O_CombatUniform_oucamo", // Fatigues (Urban) [CSAT] UNIFORM"
	"U_O_GhillieSuit", // Ghillie Suit [CSAT] UNIFORM"
	"U_O_OfficerUniform_ocamo", // Officer Fatigues (Hex) UNIFORM"
	"U_O_PilotCoveralls", // Pilot Coveralls [CSAT] UNIFORM"
	"U_O_SpecopsUniform_ocamo", // Recon Fatigues (Hex) UNIFORM"
	"U_O_T_Officer_F", // Officer Fatigues (Green Hex) [CSAT] UNIFORM"
	"U_O_T_Soldier_F", // Fatigues (Green Hex) [CSAT] UNIFORM"
	"U_O_Wetsuit", // Wetsuit [CSAT] UNIFORM"
	"U_Rangemaster" // Rangemaster Suit UNIFORM"
];
// Set Vests: Any vests
vestsLoot =
[
	"V_BandollierB_blk", // Slash Bandolier (Black) VEST"
	"V_BandollierB_cbr", // Slash Bandolier (Coyote) VEST"
	"V_BandollierB_ghex_F", // Slash Bandolier (Green Hex) VEST"
	"V_BandollierB_khk", // Slash Bandolier (Khaki) VEST"
	"V_BandollierB_oli", // Slash Bandolier (Olive) VEST"
	"V_BandollierB_rgr", // Slash Bandolier (Green) VEST"
	"V_Chestrig_blk", // Chest Rig (Black) VEST"
	"V_Chestrig_khk", // Chest Rig (Khaki) VEST"
	"V_Chestrig_oli", // Chest Rig (Olive) VEST"
	"V_Chestrig_rgr", // Chest Rig (Green) VEST"
	"V_HarnessOGL_brn", // LBV Grenadier Harness VEST"
	"V_HarnessOGL_ghex_F", // LBV Grenadier Harness (Green Hex) VEST"
	"V_HarnessOGL_gry", // LBV Grenadier Harness (Grey) VEST"
	"V_HarnessO_brn", // LBV Harness VEST"
	"V_HarnessO_ghex_F", // LBV Harness (Green Hex) VEST"
	"V_HarnessO_gry", // LBV Harness (Grey) VEST"
	"V_PlateCarrier1_blk", // Carrier Lite (Black) VEST"
	"V_PlateCarrier1_rgr", // Carrier Lite (Green) VEST"
	"V_PlateCarrier1_rgr_noflag_F", // Carrier Lite (Green, No Flag) VEST"
	"V_PlateCarrier1_tna_F", // Carrier Lite (Tropic) VEST"
	"V_PlateCarrier2_blk", // Carrier Rig (Black) VEST"
	"V_PlateCarrier2_rgr", // Carrier Rig (Green) VEST"
	"V_PlateCarrier2_rgr_noflag_F", // Carrier Rig (Green, No Flag) VEST"
	"V_PlateCarrier2_tna_F", // Carrier Rig (Tropic) VEST"
	"V_PlateCarrierGL_blk", // Carrier GL Rig (Black) VEST"
	"V_PlateCarrierGL_mtp", // Carrier GL Rig (MTP) VEST"
	"V_PlateCarrierGL_rgr", // Carrier GL Rig (Green) VEST"
	"V_PlateCarrierGL_tna_F", // Carrier GL Rig (Tropic) VEST"
	"V_PlateCarrierH_CTRG", // CTRG Plate Carrier Rig Mk.2 (Heavy) VEST"
	"V_PlateCarrierIA1_dgtl", // GA Carrier Lite (Digi) VEST"
	"V_PlateCarrierIA2_dgtl", // GA Carrier Rig (Digi) VEST"
	"V_PlateCarrierIAGL_dgtl", // GA Carrier GL Rig (Digi) VEST"
	"V_PlateCarrierIAGL_oli", // GA Carrier GL Rig (Olive) VEST"
	"V_PlateCarrierL_CTRG", // CTRG Plate Carrier Rig Mk.1 (Light) VEST"
	"V_PlateCarrierSpec_blk", // Carrier Special Rig (Black) VEST"
	"V_PlateCarrierSpec_mtp", // Carrier Special Rig (MTP) VEST"
	"V_PlateCarrierSpec_rgr", // Carrier Special Rig (Green) VEST"
	"V_PlateCarrierSpec_tna_F", // Carrier Special Rig (Tropic) VEST"
	"V_PlateCarrier_Kerry", // US Plate Carrier Rig (Kerry) VEST"
	"V_Rangemaster_belt", // Rangemaster Belt VEST"
	"V_RebreatherB", // Rebreather [NATO] VEST"
	"V_RebreatherIA", // Rebreather [AAF] VEST"
	"V_RebreatherIR", // Rebreather [CSAT] VEST"
	"V_TacChestrig_cbr_F", // Tactical Chest Rig (Coyote) VEST"
	"V_TacChestrig_grn_F", // Tactical Chest Rig (Green) VEST"
	"V_TacChestrig_oli_F", // Tactical Chest Rig (Olive) VEST"
	"V_TacVestIR_blk", // Raven Vest VEST"
	"V_TacVest_blk", // Tactical Vest (Black) VEST"
	"V_TacVest_brn", // Tactical Vest (Brown) VEST"
	"V_TacVest_camo", // Tactical Vest (Camo) VEST"
	"V_TacVest_khk", // Tactical Vest (Khaki) VEST"
	"V_TacVest_oli" // Tactical Vest (Olive) VEST"
];
// Set Backpacks: Any packpacks
backpacksLoot =
[
	"B_AssaultPack_blk", // Assault Pack (Black) BACKPACK"
	"B_AssaultPack_cbr", // Assault Pack (Coyote) BACKPACK"
	"B_AssaultPack_dgtl", // Assault Pack (Digi) BACKPACK"
	"B_AssaultPack_Kerry", // US Assault Pack (Kerry) BACKPACK"
	"B_AssaultPack_khk", // Assault Pack (Khaki) BACKPACK"
	"B_AssaultPack_mcamo", // Assault Pack (MTP) BACKPACK"
	"B_AssaultPack_ocamo", // Assault Pack (Hex) BACKPACK"
	"B_AssaultPack_rgr", // Assault Pack (Green) BACKPACK"
	"B_AssaultPack_sgg", // Assault Pack (Sage) BACKPACK"
	"B_AssaultPack_tna_F", // Assault Pack (Tropic) BACKPACK"
	// "B_Bergen_dgtl_F", // Bergen Backpack (Digital) BACKPACK"
	// "B_Bergen_hex_F", // Bergen Backpack (Hex) BACKPACK"
	// "B_Bergen_mcamo_F", // Bergen Backpack (MTP) BACKPACK"
	// "B_Bergen_tna_F", // Bergen Backpack (Tropic) BACKPACK"
	"B_Carryall_cbr", // Carryall Backpack (Coyote) BACKPACK"
	"B_Carryall_ghex_F", // Carryall Backpack (Green Hex) BACKPACK"
	"B_Carryall_khk", // Carryall Backpack (Khaki) BACKPACK"
	"B_Carryall_mcamo", // Carryall Backpack (MTP) BACKPACK"
	"B_Carryall_ocamo", // Carryall Backpack (Hex) BACKPACK"
	"B_Carryall_oli", // Carryall Backpack (Olive) BACKPACK"
	"B_Carryall_oucamo", // Carryall Backpack (Urban) BACKPACK"
	"B_FieldPack_blk", // Field Pack (Black) BACKPACK"
	"B_FieldPack_cbr", // Field Pack (Coyote) BACKPACK"
	"B_FieldPack_ghex_F", // Field Pack (Green Hex) BACKPACK"
	"B_FieldPack_khk", // Field Pack (Khaki) BACKPACK"
	"B_FieldPack_ocamo", // Field Pack (Hex) BACKPACK"
	"B_FieldPack_oli", // Field Pack (Olive) BACKPACK"
	"B_FieldPack_oucamo", // Field Pack (Urban) BACKPACK"
	"B_Kitbag_cbr", // Kitbag (Coyote) BACKPACK"
	"B_Kitbag_mcamo", // Kitbag (MTP) BACKPACK"
	"B_Kitbag_rgr", // Kitbag (Green) BACKPACK"
	"B_Kitbag_sgg", // Kitbag (Sage) BACKPACK"
	"B_TacticalPack_blk", // Tactical Backpack (Black) BACKPACK"
	"B_TacticalPack_mcamo", // Tactical Backpack (MTP) BACKPACK"
	"B_TacticalPack_ocamo", // Tactical Backpack (Hex) BACKPACK"
	"B_TacticalPack_oli", // Tactical Backpack (Olive) BACKPACK"
	"B_TacticalPack_rgr", // Tactical Backpack (Green) BACKPACK"
	"B_ViperHarness_blk_F", // Viper Harness (Black) BACKPACK"
	"B_ViperHarness_ghex_F", // Viper Harness (Green Hex) BACKPACK"
	"B_ViperHarness_hex_F", // Viper Harness (Hex) BACKPACK"
	"B_ViperHarness_khk_F", // Viper Harness (Khaki) BACKPACK"
	"B_ViperHarness_oli_F", // Viper Harness (Olive) BACKPACK"
	"B_ViperLightHarness_blk_F", // Viper Light Harness (Black) BACKPACK"
	"B_ViperLightHarness_ghex_F", // Viper Light Harness (Green Hex) BACKPACK"
	"B_ViperLightHarness_hex_F", // Viper Light Harness (Hex) BACKPACK"
	"B_ViperLightHarness_khk_F", // Viper Light Harness (Khaki) BACKPACK"
	"B_ViperLightHarness_oli_F" // Viper Light Harness (Olive) BACKPACK"
];

// Exclude buildings from loot spawn. Use 'TYPEOF' to find building name
_exclusionList =
[
	"Land_Pier_F",
	"Land_Pier_small_F",
	"Land_NavigLight",
	"Land_LampHarbour_F"
];

private ["_distance","_houseList"];

_mkr = BRCQC_mkr_blackZone;
_pos = markerPos _mkr;
_mkrY = abs(getMarkerSize _mkr select 0);
_mkrX = abs(getMarkerSize _mkr select 1);

_distance = _mkrX;
if (_mkrY > _mkrX) then
{
	_distance = _mkrY;
};

_houseList = nearestObjects [_pos,["House","HouseBase","Ruins","House_F","Ruins_F"],_distance];

{
	_house = _x;
	if !((typeOf _house) in _exclusionList) then
	{
			_houseNumPos = count (_house buildingPos -1);
			if (_houseNumPos >= 1) then
			{
				for "_n" from 0 to (_houseNumPos - 1) do
				{
					_buildingPos = _house buildingPos _n;
					if !(_buildingPos isEqualTo [0,0,0]) then
					{
						if ((_insideProbability > random 100) || (_insideProbability isEqualTo 100)) then
						{
							[_buildingPos,_showLoot] spawn BRCQC_fnc_lootSpawnInside;
						};	
					};
				};
			};
			// for buildings with 0 building positions, loop max 3 times.
			if (_houseNumPos == 0) then 
			{
				for [{_n = 0},{_n < 3},{_n = _n + 1}] do
				{
					_buildingPos = [0,0,0];
					_buildingPosCount = 1;
					_buildingPosOK = false;
					while {!_buildingPosOK} do
					{
						_buildingPos = getPos _house findEmptyPosition [0,_buildingPosCount,"Land_WoodenLog_F"];
						if !(_buildingPos isEqualTo []) then
						{
							_buildingPosOK = true;
							_intersectDetails = lineIntersectsSurfaces [ATLToASL _buildingPos, [(_buildingPos select 0),(_buildingPos select 1),-1000]];
							_buildingPos = ASLToATL ((_intersectDetails select 0) select 0);
							_buildingPos set [2,(_buildingPos select 2) + 0.02];
						};
						_buildingPosCount = _buildingPosCount + 1;
					};
					if !(_buildingPos isEqualTo [0,0,0]) then
					{
						if ((_outsideProbability > random 100) || (_outsideProbability isEqualTo 100)) then
						{
							[_buildingPos,_showLoot] spawn BRCQC_fnc_lootSpawnOutside;

						};	
					};
				};
			};
	};
	sleep 0.1;
} forEach _houseList;

diag_log format ["[BRCQC] LOOT SPAWNED IN %1 HOUSES",(count _houseList)];

sleep 5;

BRCQC_var_playZoneLoot = false;
