// 0 = 100%
// 1 = 50%
// 2 = 25%
// 3 = 12.5%

CIV = 0; //100%
MIL = 1; //50%
RARE_CIV = 2; //25%
RARE_MIL = 3; //12.5%

MAG = 0;
WEAPON = 1;
ITEM = 2;
PACK = 3;
BRMini_Loot = [
	["hgun_P07_F",WEAPON,CIV,1],
	["hgun_Rook40_F",WEAPON,MIL,1],
	["hgun_ACPC2_snds_F",WEAPON,CIV,1],
	["hgun_Rook40_snds_F",WEAPON,MIL,1],
	["16Rnd_9x21_Mag",MAG,CIV,1],
	["hgun_ACPC2_F",WEAPON,CIV,1],
	["9Rnd_45ACP_Mag",MAG,MIL,1],
	["SMG_01_F",WEAPON,RARE_MIL,1],
	["SMG_02_F",WEAPON,RARE_MIL,1],
	["hgun_Pistol_heavy_01_F",WEAPON,RARE_CIV,1],
	["11Rnd_45ACP_Mag",MAG,MIL,1],
	["hgun_Pistol_heavy_02_F",WEAPON,RARE_CIV,1],
	["6Rnd_45ACP_Cylinder",MAG,MIL,1],
	["hgun_PDW2000_F",WEAPON,RARE_MIL,1],
	["muzzle_snds_L",ITEM,MIL,1],
	["muzzle_snds_acp",ITEM,MIL,1],
	["optic_Holosight_smg",ITEM,RARE_CIV,1],
	["optic_Hamr",ITEM,RARE_CIV,1],
	["optic_Arco",ITEM,RARE_MIL,1],
	["optic_Aco",ITEM,RARE_CIV,1],
	["optic_ACO_grn",ITEM,RARE_CIV,1],
	["optic_MRCO",ITEM,RARE_MIL,1],
	["optic_DMS",ITEM,RARE_MIL,1],
	["optic_Yorris",ITEM,MIL,1],
	["optic_MRD",ITEM,MIL,1],
	["FirstAidKit",ITEM,CIV,1],
	["MineDetector",ITEM,MIL,1],
	["SmokeShell",ITEM,CIV,1],
	["SmokeShellRed",ITEM,CIV,1],
	["SmokeShellBlue",ITEM,CIV,1],
	["SmokeShellGreen",ITEM,CIV,1],
	["SmokeShellOrange",ITEM,CIV,1],
	["SmokeShellPurple",ITEM,CIV,1],
	["APERSTripMine_Wire_Mag",ITEM,RARE_MIL,1],
	["HandGrenade",ITEM,MIL,1],
	["MiniGrenade",ITEM,MIL,1],
	["HandGrenade",ITEM,MIL,1],
	["B_AssaultPack_blk",PACK,CIV,1],
	["B_AssaultPack_cbr",PACK,CIV,1],
	["B_AssaultPack_dgtl",PACK,CIV,1],
	["B_AssaultPack_khk",PACK,CIV,1],
	["B_AssaultPack_mcamo",PACK,CIV,1],
	["B_AssaultPack_ocamo",PACK,CIV,1],
	["B_Bergen_mcamo",PACK,MIL,1],
	["B_Bergen_blk",PACK,MIL,1],
	["B_Bergen_sgg",PACK,MIL,1],
	["FirstAidKit",ITEM,CIV,1],
	["B_FieldPack_blk",PACK,MIL,1],
	["B_AssaultPack_rgr",PACK,MIL,1],
	["B_AssaultPack_sgg",PACK,MIL,1],
	["B_HuntingBackpack",PACK,MIL,1],
	["B_OutdoorPack_blu",PACK,MIL,1],
	["U_B_Wetsuit",ITEM,MIL,1],
	["U_I_CombatUniform",ITEM,CIV,1],
	["V_Chestrig_blk",ITEM,CIV,1],
	["V_HarnessO_brn",ITEM,CIV,1],
	["V_BandollierB_blk",ITEM,CIV,1],
	["V_TacVestCamo_khk",ITEM,CIV,1],
	["U_OG_Guerilla1_1",ITEM,CIV,1],
	["U_BG_leader",ITEM,CIV,1],
	["V_Press_F",ITEM,CIV,1],
	["U_I_CombatUniform_shortsleeve",ITEM,CIV,1],
	["V_Chestrig_blk",ITEM,CIV,1],
	["V_HarnessOGL_brn",ITEM,CIV,1],
	["V_HarnessOSpec_brn",ITEM,CIV,1],
	["V_TacVestCamo_khk",ITEM,CIV,1],
	["V_TacVest_blk_POLICE",ITEM,CIV,1],
	["V_TacVest_khk",ITEM,MIL,1],
	["V_TacVest_oli",ITEM,MIL,1],
	["U_OG_Guerilla1_1",ITEM,CIV,1],
	["FirstAidKit",ITEM,CIV,1],
	["U_B_SpecopsUniform_sgg",ITEM,CIV,1],
	["U_OG_Guerilla1_1",ITEM,CIV,1],
	["U_O_CombatUniform_oucamo",ITEM,CIV,1],
	["V_TacVestIR_blk",ITEM,MIL,1],
	["V_TacVest_blk",ITEM,MIL,1],
	["V_TacVest_brn",ITEM,MIL,1],
	["V_PlateCarrierSpec_rgr",ITEM,RARE_MIL,1],
	["V_PlateCarrier1_blk",ITEM,RARE_MIL,1],
	["U_O_Wetsuit",ITEM,RARE_MIL,1],
	["U_B_GhillieSuit",ITEM,RARE_MIL,1],
	["APERSBoundingMine_Range_Mag",ITEM,RARE_MIL,1],
	["APERSMine_Range_Mag",ITEM,RARE_MIL,1],
	["ClaymoreDirectionalMine_Remote_Mag",ITEM,RARE_MIL,1],
	["SatchelCharge_Remote_Mag",ITEM,RARE_MIL,1],
	["SLAMDirectionalMine_Wire_Mag",ITEM,RARE_MIL,1]	
];